#ifndef INCLUDE_GUARD
#define INCLUDE_GUARD

#define _CERBERUS_VERSION       "3.0.1"
#define _CERBERUS_VERSION_MAJOR "3"
#define _CERBERUS_VERSION_MINOR "0"
#define _CERBERUS_VERSION_PATCH "1"

#endif
