#ifndef INCLUDE_GUARD
#define INCLUDE_GUARD

#define _CERBERUS_VERSION       "2.1.0"
#define _CERBERUS_VERSION_MAJOR "2"
#define _CERBERUS_VERSION_MINOR "1"
#define _CERBERUS_VERSION_PATCH "0"

#endif
